### ISSUE TITLE
Windows 10X support (not urgent)

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1087]
Currently, Files UWP doesn't run on Windows 10X. We should add Windows 10X support for Files UWP.

**Steps to reproduce:**

- Download Microsoft Emulator and Windows 10X image.
- Go to Files UWP's Microsoft Store listing on the emulator.
-  It will say your PC isn't supported.

**Comment by yaichenbaum** [comment]
Windows 10X is definitely on our radar and as soon as it's posible we will start supporting it. Files UWP is not currently supported on Windows 10X because is falls between the containers. Windows 10X has a Win32 container and a UWP container, because Files UWP includes a win32 component and the main component is UWP, Files UWP doesn't fit in any of the containers in Windows 10X and is therefore unsupported.
