### ISSUE TITLE
Some Requests

### ISSUE THREAD

**Issue by AbelTheGeorge** [files-community/files-uwp#1132]
Here are some suggestions... Amazing program btw

In the default explorer pressing alt and clicking opens the properties of the clicked item... please implement it if possible...I have grown used to it

Im not sure about all the current keyboard shortcuts but... Some shortcut for Closing current tab ... Opening accidentally closed tab ...like the cntrl+ q and cntrl + shift + t shortcuts in google chrome would be highly appreciated along with an option to customize the keyboard shortcuts...

Another thing which im not sure is possible but would be highly appreciated ... is the option to directly eject external storage media from the navigation pane by right clicking and selecting eject.

An option to resize the different sections of the program like increasing or decreasing the width of the navigation pane.

**Comment by duke7553** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.

**Comment by XPoppyX** [comment]
1 - Comment here: #9 ,the keyboard shortcuts that you would like to be supported
2 - Add the option to eject drives #84
3- Ability to resize the sidebar #672
