### ISSUE TITLE
UI improvements for title bar / tab bar

### ISSUE THREAD

**Issue by jayasio** [files-community/files-uwp#1193]
**Is your feature request related to a problem? Please describe.**
Right now, the app uses tab metaphors similar to Edge Chromium.
In Edge, it can be seen that there is a small gap between tab and top edge of app **only when the app is NOT maximized to fullscreen.** In other cases, there is no gap.

![Screenshot (39)_LI](https://user-images.githubusercontent.com/34701149/85244871-838c6680-b463-11ea-95c1-2505e9f3c3fc.jpg)
![Screenshot (38)](https://user-images.githubusercontent.com/34701149/85244875-87b88400-b463-11ea-84c7-ee266a544da6.png)

This is to let the user drag and move the window when it's not fullscreen. 
Coming to a similar issue, a gap is left at the top-left corner of Edge Chromium for two reasons:
1. The tab has an outward curve in the bottom (this is not the main reason)
2. The gap is for the user to drag and move the window even when full-screen

![Screenshot (40)_LI](https://user-images.githubusercontent.com/34701149/85245203-7d4aba00-b464-11ea-8790-3fc0869c72a2.jpg)
![Screenshot (41)_LI](https://user-images.githubusercontent.com/34701149/85245234-9c494c00-b464-11ea-8cc4-7e6ccfdc3ff4.jpg)

In the above image, 
(1) is not required at all
(2) is required only when app is not fullscreen (also let user drag and move in that area)
(3) must support drag and move

With the implementation of (3), (2) can be ignored since Edge Chromium does that only since it doesn't have a space like the sidebar. This will look similar to the actual proposal of Windows Sets, with the modern visual style of Edge Chromium.

**Describe the solution you'd like**
In Files UWP, I propose a few changes:
1. Since there is a sidebar, the top left gap of tabs in Edge chromium need not be replicated.
2. The space above the sidebar elements must let the user drag and move the window.
3. Once these two are implemented, the top gap above the tabs can be removed when fullscreen.
This will improve the visual layout too, by providing a natural division between sidebar and tabs; right now, the top-left gap is breaking the UI.

**Comment by yaichenbaum** [comment]
The gaps around the tabs are mainly to keep a separation in the three parts of the UI (tabs, sidebar and file browser). It's a little hard to compare the app to Edge as that has two main components (the url bar and the webview). However being that tabs are not for everyone, we are working on an option to hide the tabs.

**Comment by jayasio** [comment]
Hiding tabs is nice.
I still think the gaps are creating issues; For example, the gaps and sidebar being both Acrylic, it feels like the sidebar is independent of the tabs, and the explorer (tabs and explorer look like they're placed above the Acrylic), but it's actually not.

#664 is something I'm referring to as a better solution, with respect to tabs alone. 

![Screenshot (43)](https://user-images.githubusercontent.com/34701149/85247828-aa02cf80-b46c-11ea-88d1-f0a5379e03f1.png)
The sidebar is not actually an independent part of the UI, it is closely related to the tab that's shown. Switching the tab changes the highlighted option in the sidebar, and so technically the metaphor is that the sidebar belongs to the tab. See how the highlight on "Home" overlaps with the tab bar? So the separation between sidebar and explorer must be a hard line; now that I look at it, the area (3) must be fully blank to match the height tab bar. 

There's a clash of metaphor in the UI.

(I want to discuss the smaller side of the UI since I appreciate the project and my contributions can only be from the UI/UX side; I hope it's okay since it's not as big as a code issue/feature.)

**Comment by jayasio** [comment]
![Screenshot (43)](https://user-images.githubusercontent.com/34701149/85249889-93f80d80-b472-11ea-9491-0e4910244508.png)

Roughly, this creates an invisible line on the title bar, including the title ('Files'). The 'Files', tabs, and minimise, maximise, close controls fall into a single title bar. The sidebar is an extension of the tab content. In a high contrast theme or transparency disabled, the separation will be much prominent.

**Comment by duke7553** [comment]
I feel strongly that @jayasio is correct on this one. 

There are two notable problems with our current layout which may cause subconscious confusion among users:

1. Being extended to the top region of the app, the sidebar is independent of its adjacent content because the TabView is placed next to it. This is incorrect.
2. The sidebar also shares the same material as the titlebar background which implies they are on the same footing.

We are working on allowing users to hide the TabView altogether, which requires decoupling of the content page from the TabView. With that said, users who love multitasking with tabs, we hear you loud and clear! 

These users opting to use the TabView will have a slightly different experience compared to what is available today. We're hoping to not only correct the broken design metaphor existing in the app, but also provide genuine improvements to the TabView where needed. While we have no concrete release date, we're hoping to improve:
- Personality: How much information does each open tab reveal? What makes each tab different besides an icon and text?
- Multi-tasking: How difficult is it to work between tabs?
- Consumption: In what ways can we reduce clutter and bring focus to the relevant content itself.

We'll post screenshots of the new implementation as they're ready.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. A solution to this issue is currently resolved in one of our active development branches and will be shipped after we've validated that everything works properly via code review. 

We will notify you when this feature is in a PR
