### ISSUE TITLE
Few features needed

### ISSUE THREAD

**Issue by Xemanth** [files-community/files-uwp#1227]
For start, you have made an amazing UWP Files app! I'm in love <3

Here's my list of features which would be nice to have:
1) Add ability to pin files to the sidebar
2) Add more categories to sidebar like Hotpluggable USB sticks, now they are in Drives category
4) USB storage sticks need unmount button next to them
5) Add ability to reorganize pinned folders
6) Recent items need dates when files are opened
7) Files need "Copy path" -button to the secondary menu. Now it's possible to Copy path to the open folder via 3 dots menu.
8) The address bar needs a switch to allow FQDN path to be always available. Now it needs clicking.
9) Add quick shortcut button to Settings:clean -dialog, maybe inside Settings-button some clean page or something.

For now, these are the features that came to my mind.

Thx!

**Comment by XPoppyX** [comment]
1- #287 
3- #84 
4- #1069

**Comment by duke7553** [comment]
@Xemanth Can you open these as separate tickets, if not already open? 

Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
