### ISSUE TITLE
MTP based storage crashes the app

### ISSUE THREAD

**Issue by far1998** [files-community/files-uwp#1403]
Everytime I open MTP based storage, eg. phone/camera, it crashes the app. It seemingly like MTP based storage broken the app, cannot be opened or not functioning in this app. Please fix.

**Comment by yaichenbaum** [comment]
@far1998 What version of the app are you using?

**Comment by far19a** [comment]
Latest version today Sent from Mail for Windows 10 From: Yair yair100: 12 July 2020 23:58To: files-community/files-uwpCc: far1998; MentionSubject: Re: [files-community/files-uwp] MTP based storage crashes the app (#1403) @far1998 What version of the app are you using?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yaichenbaum** [comment]
@far1998 This issue should be fixed in v0.12.
