### ISSUE TITLE
Add support for Control Panel (not working)

### ISSUE THREAD

**Issue by seohyun1108** [files-community/files-uwp#1433]
**Is your feature request related to a problem? Please describe.**
After I set Files UWP to default file explorer, Control Panel does not work anymore. Files UWP opens when I open Control Panel :(

**Describe the solution you'd like**
I think it's hard to make a new Control Panel. So, please add support for Control Panel.

**Comment by Jaiganeshkumaran** [comment]
This occurs because the control panel is part of File Explorer and making Files UWP default will open all links in Files UWP instead of Files UWP. We can check if the link is a control panel link and then open the control panel.

**Comment by seohyun1108** [comment]
So is there any solutions?

**Comment by Jaiganeshkumaran** [comment]
@seohyun1108 We can redirect the user from Files UWP to Control Panel if the link is a control panel link. However, Files UWP will still start and the Control Panel will only appear after Files UWP starts since you can't launch the control panel directly anymore. Instead, I recommend you not to replace File Explorer with Files UWP until all control panel applets are migrated to the Windows Settings app.  You can add a context menu option to open a selected folder in Files UWP instead. Check this out: https://github.com/files-community/files-uwp/wiki/Add-Files-UWP-to-the-File-Explorer-context-menu
