### ISSUE TITLE
I want to use it as deafult( please add an option) also add new features * sorting,better scroll on touch

### ISSUE THREAD

**Issue by fisforfaheem** [files-community/files-uwp#1450]
I want this app to be by daily driver and default, but no option please add new thing sin experimental also , make more features before microsoft launches windows 10x

**Comment by Jaiganeshkumaran** [comment]
You can already set Files UWP as the default by modifying the [Windows Registry](https://github.com/files-community/files-uwp/wiki/Replacing-File-Explorer-with-Files-UWP) however, please don't since it breaks core Windows functionality like the Control Panel. Instead, you can add a right-click menu option to open a selected folder with Files UWP. Check this out: https://github.com/files-community/files-uwp/wiki/Add-Files-UWP-to-the-File-Explorer-context-menu
