### ISSUE TITLE
files on desktop don't open with it.

### ISSUE THREAD

**Issue by techtanic** [files-community/files-uwp#1464]
I don't know if I am dumb but the files on the desktop don't open with file - uwp .
and also win+E only opens the old explorer.

**Comment by Jaiganeshkumaran** [comment]
@techtanic Yes you're dumb, not really. Folders open in File Explorer by default and installing a third-party file manager doesn't replace it. You need to modify the registry to achieve that but you can't access the control panel since it's part of the File Explorer. Instead, I would suggest you add an option to open a selected folder in Files UWP. You can learn both in the wiki.

**Comment by techtanic** [comment]
> @techtanic Yes you're dumb, not really. Folders open in File Explorer by default and installing a third-party file manager doesn't replace it. You need to modify the registry to achieve that but you can't access the control panel since it's part of the File Explorer. Instead, I would suggest you add an option to open a selected folder in Files UWP. You can learn both in the wiki.

link pls?

**Comment by Jaiganeshkumaran** [comment]
It's there in the nav bar itself.
