### ISSUE TITLE
What happened to the tabs?

### ISSUE THREAD

**Issue by ArttuLai** [files-community/files-uwp#1564]
Maybe I missed the news, but I see that the tabs were removed in the later preview builds. Or at least, moved behind multitasking flyout.

I'm sure you guys worked hard on this flyout too, and you can do whatever you want with your app, but I'm just trying to understand why would you choose to go with this implementation?

I find this flyout menu cumbersome to use, you always have to click it first to see the tabs, adding an extra step to every action. There's no visual indication which tabs or how many are open, which one you're in, which is the "tab 1" or "tab 2" etc.

I don't wanna sound rude but I think this flyout singlehandedly ruins the usability/UX of this app. I hope you could reconsider bringing back the old behavior.

(Or maybe we're just in the middle of something and I'm jumping the gun / overreacting. If so, I'm sorry).

**Comment by duke7553** [comment]
The old behavior probably isn't coming back for a number of reasons, but we'll take this feedback into consideration when improving the flyout. 

@ArttuLai Did you know you can access the flyout by hovering over the icon, and hovering off the flyout to close it?

**Comment by generalguy41** [comment]
> 
> 
> The old behavior probably isn't coming back for a number of reasons, but we'll take this feedback into consideration when improving the flyout.
> 
> @ArttuLai Did you know you can access the flyout by hovering over the icon, and hovering off the flyout to close it?

@duke7553 Can you elaborate those reasons? Or link to the discussion/feedback that took place regarding removing it? Maybe I just missed my chance to put in my input. I'm personally not a fan at all of the extra steps that it's now going to take to work with tabs. The tabs in their previous form were something that set this apart for me from other UWP file explorer replacements and really made it stand out. I'm honestly disappointed they were removed entirely without even an option to keep the original system.

**Comment by duke7553** [comment]
See https://github.com/files-community/files-uwp/issues/1193

**Comment by XPoppyX** [comment]
if there are visual issues with the rounded corners it would be better to reverse that change instead of making a big change like removing the tabs

**Comment by ArttuLai** [comment]
@duke7553 I think you guys jumped the gun a bit here: fixing a "clashing design metaphor" by nuking the standout/signature/main feature of the app sounds like an overkill. I think it looked/worked great before, and could've been improved further without having to alter it so drastically. I just feel like that decision was made by designers nitpicking on some design metaphors "normal" users probably never even noticed — I sure didn't, and I even count myself as someone who loves and cares about design.

I think the new way is way more confusing as they're called *tabs* but don't work like any other *tab* in apps we're used to. I'd go as far as to say this is even more clashing design metaphor than the conjoined of sidebar & titlebar.

I tried the hover, it was even slower to use, I think it all comes down to quickness of use. Thanks for the tip and reply though.

**Comment by SOI7** [comment]
tbf I think OP in #1193 simply wanted the gaps to go 🤷‍♂️

**Comment by generalguy41** [comment]
The biggest concern I'm seeing in that issue is a supposed perceived issue among users that the gaps around the tabs would be confusing? Feel free to correct me if I'm wrong. 

I recognize that there are issues with:
- the section above the tabs and above the 'Home' button that are not draggable. 
- the curve on the leftmost side of the first tab when selected is not clean with the sidebar

I don't recognize how the titlebar and sidebar both being acrylic is an actual issue to users. Have there been complaints that users don't know what tab they're on? Obviously I can't relate to the average user, but it seems straightforward to me that the tab that matches the background colour is the active tab...

I think my biggest issue is with this line here (emphasis my own):

> We are working on _**allowing users**_ to hide the TabView altogether, which requires decoupling of the content page from the TabView. With that said, users who love multitasking with tabs, we hear you loud and clear!

Everything I've read so far has been that this new format will be replacing the TabView entirely and there's no going back. So instead of individually addressing the issues listed in the ticket(s), the solution was to just remove it entirely? I'd also be interested to know why any of the recommendations ([1193](https://github.com/files-community/files-uwp/issues/1193#issuecomment-647276814), [664](https://github.com/files-community/files-uwp/issues/664), [279](https://github.com/files-community/files-uwp/issues/279)) were or weren't implemented (again, maybe there was discussion on this, but I don't remember seeing it. Links would be appreciated.)

Look, I don't mean for this to come off as aggressively as it probably does. I understand that you all are putting in tons of work to make the app as great as it can be, and I think you've done a phenomenal job at that. I'm just really disheartened that one of the standout features has been removed entirely without much discussion.

**Comment by duke7553** [comment]
I'll make an announcement soon which I'm sure everyone will like.

In the meantime, what aspects of a horizontal TabView are important to you?

@SOI7 @ArttuLai @generalguy41

**Comment by mdtauk** [comment]
Firstly, Seeing all the folders/locations I have open is impotant for me.  

Secondarily is the ability to click on them to switch to that location's Icon View.  

Thirdly, the ability to drag a group of files or files and folders, from on icon view, hover over a tab, the tab switches, and I can let go of the mouse within that location's icon view, to move the items.

Throw in the ability to hover over the tab to show a tooltip with the full path to that folder as a nice cherry on the cake.

**Comment by duke7553** [comment]
> Everything I've read so far has been that this new format will be replacing the TabView entirely and there's no going back.

The changes included with the Vertical Tabs actually were done with anticipation of user feedback on our design decisions. I'm in the process of working out the details for this new initiative, but please don't fret. There's always ways to go back, and the changes I made only enable that further. Once the announcement is made, our goal will be to create something better than both previous implementations. 

Our mistake in this last one was not working with the community enough, so I understand your pain points completely and changed my mind on this.

**Comment by ArttuLai** [comment]
Thanks, sounds exciting!

1. I'd say one-click access to different tabs is the key thing for me
2. Being able to see all of the tabs that are open at once, and being able to reorganize them, close them with one click, open a new tab like in Edge (+) button
3. Drag & drop files with one hand: take a file in tab1, drag it over tab2 to move it to that folder

**Comment by generalguy41** [comment]
> 
> 
> I'll make an announcement soon which I'm sure everyone will like.
> 
> In the meantime, what aspects of a horizontal TabView are important to you?

![image](https://user-images.githubusercontent.com/8879244/88417594-311ace80-cdb0-11ea-871a-5c5d8bd47d62.png)

Jokes aside, I really like the ease of being able to see which tabs I have open/access to at a glance. I was really looking forward to the work of being able to drag/drop things across tabs as well, and think that would be the easiest method rather than having to deal with hovering over an icon, then scrolling down a flyout list to find the correct tab.

**Comment by SOI7** [comment]
> I'll make an announcement soon which I'm sure everyone will like.
> 
> In the meantime, what aspects of a horizontal TabView are important to you?
> 
> @SOI7 @ArttuLai @generalguy41

The most important aspect of horizontal TabView, to me, is it being streamlined with the UI at eye-sight, plus it allows me to quickly switch folders and speed up my workflow. In an ideal complete Tab system I should also be able to drag and drop files from one tab to another, which technically doesn't really matter atm, but it would be much easier to do that in a horizontal layout compared to a buried vertical flyout. Also, I personally find it visually much more elegant, and it's an aspect to not underestimate in a UWP.

Side Note: I come from Clover and QTTabbar, horizontal tabs are one of my dirtiest desires that Microsoft is insisting to not implement in W10's File Explorer, and it's my n°1 feature that encourages me to use Files UWP over the legacy one (apart from Fluent Design of course)

**Comment by yaichenbaum** [comment]
> Thanks, sounds exciting!
> 
> 1. I'd say one-click access to different tabs is the key thing for me
> 2. Being able to see all of the tabs that are open at once, and being able to reorganize them, close them with one click, open a new tab like in Edge (+) button
> 3. Drag & drop files with one hand: take a file in tab1, drag it over tab2 to move it to that folder

1. This is already possible with the new implementation, we do have some improvements to make to the speed, however it isn't specific to the vertical tab flyout.
2. Adding a button to add a new tab is definitely something we could do.
3. This is already possible in the latest preview.

**Comment by yaichenbaum** [comment]
> I think you guys jumped the gun a bit here: fixing a "clashing design metaphor" by nuking the standout/signature/main feature of the app sounds like an overkill. I think it looked/worked great before, and could've been improved further without having to alter it so drastically. I just feel like that decision was made by designers nitpicking on some design metaphors "normal" users probably never even noticed — I sure didn't, and I even count myself as someone who loves and cares about design.

The new changes were in the works for quite some time. Since removing the ribbon a few months ago, the tabs never really fit in, the UX confused users and the idea of having two navigation sections right next to each other caused clashing designs. The changes we made were not because of one specific issue, but rather, because of many different issues. We are planning on improving the new experience and we will continue pushing it as the default experience. However, we know there are many users who prefer the older design and we are exploring different options and listening closely to your feedback in order to  come up with the best path forward.

**Comment by yaichenbaum** [comment]
> I think you guys jumped the gun a bit here: fixing a "clashing design metaphor" by nuking the standout/signature/main feature of the app sounds like an overkill. I think it looked/worked great before, and could've been improved further without having to alter it so drastically. I just feel like that decision was made by designers nitpicking on some design metaphors "normal" users probably never even noticed — I sure didn't, and I even count myself as someone who loves and cares about design.

The changes to the tab UI were in the works for quite some time. Since removing the ribbon a few months ago, the tabs never really fit in, the UX confused users, and the idea of having two navigation sections right next to each other caused clashing designs. The changes we made were not because of one specific issue, but rather, because of many different issues. We are planning to improve the new experience and we will continue pushing it as the default experience. However, we know there are many users who prefer the older design and we are exploring different options and listening closely to your feedback to come up with the best path forward.

**Comment by Talisman39ar** [comment]
I use Stardock's Groupy (which allows tabbed UI for all applications), and I can drag a file from one File Explorer window on to another tab, that tab then becomes visible and I can drop the file into where I want in the now-visible file list. Horizontal tabs afford this as they are always visible. Maybe there's a way to do it with the vertical tab/hover menu, but it's more opaque (even with horizontal tabs it's not super obvious). This interaction is one of the benefits of MacOS column view IMO

![image](https://user-images.githubusercontent.com/61295915/88429499-c627c280-cdc4-11ea-8545-2b8f5d4fd6a9.png)

**Comment by generalguy41** [comment]
> Since removing the ribbon a few months ago, the tabs never really fit in, the UX confused users, and the idea of having two navigation sections right next to each other caused clashing designs.

I don't understand how the UX confused users. Can you explain what the common complaints were or how specifically it's confusing?

**Comment by XPoppyX** [comment]
it is much faster and more comfortable to navigate between horizontal tabs, now you should always open a menu, adding that simple extra step makes it annoying

**Comment by XPoppyX** [comment]
If there are users who find it difficult to know which tab they are in, something like this could be the solution:

**Before:**
![Anotación 2020-07-24 184125](https://user-images.githubusercontent.com/61259627/88442025-f715f080-cde0-11ea-9ab5-c5e44e2b0c37.png)


**After:**
- Change the heading to gray when it is not in focus
- And maybe change the color of the header icon to the color accent when it is in focus

![Anotación 2020-07-24 1841252](https://user-images.githubusercontent.com/61259627/88442047-02691c00-cde1-11ea-8a9a-79aa84b7b0ad.png)

**Comment by ArttuLai** [comment]
> 1. This is already possible with the new implementation, we do have some improvements to make to the speed, however it isn't specific to the vertical tab flyout.

Thanks! But if you mean that the current preview build 0.12.3.0 has "one-click tab switching", I wouldn't really call it as that (maybe you meant that you can hover over multitasking button and click a tab to switch?). What I meant is that you could see all of your open tabs at a glance, and could quickly switch between them with one click because they're always visible.

Or did you mean a build that's in the works?

Even if the hover was instant, it would still be an extra step having to aim your mouse at the small button, then following the path to the tab you want, instead of just aiming at a much wider horizontal tab once.

### About confusing users: 
I can only speak for myself but the horizontal tab layout was very intuitive to me from the moment I laid my eyes on it, whereas the flyout layout had me poking around the first minutes to even realize we still had a way to switch tabs. But yeah if you're an user who uses just one tab and sticks to it, then I can see how the new way is more clear and simple.

Horizontal tabs are such a natural navigation method in a world of today thanks to web browsers, and I'm sure everyone who knows how to navigate one, knows how to use Files UWP. The old way was such a great UI and you guys did amazing work with it, there was nothing confusing about it.

I think the old way encouraged you to use tabs and multitasking and said "you're in a tab already, we have tabs!" where the new way discourages and hides them; I guess that makes it more simple but also less useful and less powerful.

**Comment by SOI7** [comment]
> If there are users who find it difficult to know which tab they are in, something like this could be the solution:
> 
> **Before:**
> ![Anotación 2020-07-24 184125](https://user-images.githubusercontent.com/61259627/88442025-f715f080-cde0-11ea-9ab5-c5e44e2b0c37.png)
> 
> **After:**
> 
> * Change the heading to gray when it is not in focus
> * And maybe change the color of the header icon to the color accent when it is in focus
> 
> ![Anotación 2020-07-24 1841252](https://user-images.githubusercontent.com/61259627/88442047-02691c00-cde1-11ea-8a9a-79aa84b7b0ad.png)

Colored active tab icon sounds like an awesome idea 👀

**Comment by jayasio** [comment]
> > Since removing the ribbon a few months ago, the tabs never really fit in, the UX confused users, and the idea of having two navigation sections right next to each other caused clashing designs.
> 
> I don't understand how the UX confused users. Can you explain what the common complaints were or how specifically it's confusing?

For example, one issue related to #1193 would be: when the app is used in smaller sizes with multiple tabs, the top left area was confusing.. the tabs and the sidebar were occupying similar space and especially when the user switches to a tab that is not the first, it got messy since 'Home' and tab lay very close. Sure it works when on fullscreen or half split, but in a quarter split and smaller, the UI looked broken. A clear line without the curved tab would've at least sorted the sidebar out. Of course, this covers edge cases to make the app look refined, it was more of an improvement.

That said I do agree a UI modification would've sufficed rather than a whole UX change, with an extra step to look and interact with tabs. Everyone's used to horizontal tabs everywhere else and tabs are also readily present on screen all the time.

**Comment by generalguy41** [comment]
> For example, one issue related to #1193 would be: when the app is used in smaller sizes with multiple tabs, the top left area was confusing.. the tabs and the sidebar were occupying similar space and especially when the user switches to a tab that is not the first, it got messy since 'Home' and tab lay very close. Sure it works when on fullscreen or half split, but in a quarter split and smaller, the UI looked broken. A clear line without the curved tab would've at least sorted the sidebar out. Of course, this covers edge cases to make the app look refined, it was more of an improvement.
> 
> That said I do agree a UI modification would've sufficed rather than a whole UX change, with an extra step to look and interact with tabs. Everyone's used to horizontal tabs everywhere else and tabs are also readily present on screen all the time.

And these are fair points, but like you said this is more of an edge case. I agree that this should be a modification. When I first heard about the vertical tabs/menu thing, my immediate thought was "This will be great for users who use the app when the window is small. Regular sized windows will use horizontal, and once you reach a certain window size it changes to vertical". I never thought it would replace tabs entirely. The confusing tab issue is a problem regardless of what app/browser/etc you use when a window is below a certain size. I do look forward to what the proposed solution is.

**Comment by yaichenbaum** [comment]
I am closing this issue as a solution will be included in the next beta release.
