### ISSUE TITLE
关于在Windows20H2使用中发现的问题：【About using some of the questions on Windows20H2.】

### ISSUE THREAD

**Issue by XingMu-YuXi** [files-community/files-uwp#1594]
首先，它显示了一个并不存在的盘符(:D)，并且打开它会强制闪退。
其次，相应的，它没有显示全我电脑上所有的盘符，以至于他们无法在软件里打开。
再然后，建议可以增加起始页为我的电脑这个选项以方便过渡。
最后希望这个项目顺利进行，谢谢你们！
另：还是希望将来可以有自定义背景这个功能。
【First, it shows a drive letter (:D) that does not exist, and opening it will force a crash.

Secondly, correspondingly, it does not display all the drive letters on my computer, so that they cannot be opened in the software.

Then, it is recommended to add the option of starting page as my computer to facilitate the transition.

Finally, I hope this project goes smoothly, thank you!

Another: I still hope that there will be a custom background feature in the future.】

**Comment by ChihweiLHBird** [comment]
请问您一共有多少个盘符？我也是20H2版本的系统，但是我只有C盘，所以无法复现这个问题。
关于启动页面，您是希望盘符出现在画面中央吗？
![image](https://user-images.githubusercontent.com/43905414/88636575-f5ad2800-d06d-11ea-9002-d08ada4bd41a.png)

**Comment by duke7553** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.

**Comment by XingMu-YuXi** [comment]
> 请问您一共有多少个盘符？我也是20H2版本的系统，但是我只有C盘，所以无法复现这个问题。
> 关于启动页面，您是希望盘符出现在画面中央吗？
> ![image](https://user-images.githubusercontent.com/43905414/88636575-f5ad2800-d06d-11ea-9002-d08ada4bd41a.png)

六个，有一个莫名其妙冒出来的d盘，后来我是拿rx文件管理器弹出【虽然没有这个玩意】后恢复正常，希望可以帮到你。
