### ISSUE TITLE
Move floating tabs to main area

### ISSUE THREAD

**Issue by Elttob** [files-community/files-uwp#1743]
I've been using this app for a while now and have loved the clean and modern design of it so far.
However in the latest update, floating tabs don't seem to align with anything in the interface, making it look somewhat messy:

![image](https://user-images.githubusercontent.com/11815374/90312819-8e152a80-deff-11ea-9586-810b187e9507.png)

A potential improvement could be to move the floating tabs into the main area, which looks a lot better:

![image](https://user-images.githubusercontent.com/11815374/90312778-219a2b80-deff-11ea-8507-43e9438a8263.png)

**Comment by duke7553** [comment]
The reason we changed them to span the entire app width is that the TabView shouldn't be on the same level as the left Sidebar. Having them above the right side only is bad design because it implies the tabs are specific to the app content. If you can come up with ways to make the existing design feel more connected, please open a new issue.
