### ISSUE TITLE
The new right click context menu is slow when opening

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/files-uwp#1873]
The new right click context menu has a delay before it's displayed.

**Comment by yaichenbaum** [comment]
cc @gave92

**Comment by gave92** [comment]
@yaichenbaum I'm reporting here the comments made on Discord, too easy to loose info there.
The delay is mostly due to the call to the Win32 [QueryContextMenu](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-icontextmenu-querycontextmenu) function. The first time it's called it takes up to 1 sec to complete. Being an windows API call I'm not really sure you can improve this.
@Jaiganeshkumaran suggested to load the context menu items "asynchronously", showing the built-in items immediately and adding the ones from explorer when they are available. While I like this idea I'm not sure how to implement it as menu items can only be added during the `Opening` event (items added later won't be shown).
Any ideas?

**Comment by Jaiganeshkumaran** [comment]
@gave92 Use a list view that's clickable IsItemClick=True and put it inside a flyout control
