### ISSUE TITLE
Alert user trying to delete an open file.

### ISSUE THREAD

**Issue by Henboy10** [files-community/files-uwp#221]
When trying to delete a file that is open in another program, it gives me an error instead of giving me a warning simply telling me why it failed.

**Comment by yaichenbaum** [comment]
Thank you for reporting, this has been added to our list of things to do and we will update this issue when its taken care of.

**Comment by Jaiganeshkumaran** [comment]
I can fix this issue.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Thank you for jumping in! I am going to assign you this issue, if you decide you don't want to do it in the end, just let us know so we can assign it to someone else.

**Comment by Jaiganeshkumaran** [comment]
This occurs because Files UWP tries to delete the file and when it fails, it shows the exception message in a ContentDialog. While we could simply change the message, it will still show the confirmation dialog before deleting if that is enabled. A simple way to check if a file in use is to read it in a stream. If the file can't be read we could assume that the file is open.

**Comment by duke7553** [comment]
@Jaiganeshkumaran Why not just handle the exception thrown when the file is in use?

**Comment by Jaiganeshkumaran** [comment]
> @Jaiganeshkumaran Why not just handle the exception thrown when the file is in use?

It depends on what you mean by open. Some apps like notepad and the photos app don't lock their file so you can successfully delete those even if it is open.
