### ISSUE TITLE
Consider pinning files to the sidebar

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#287]
**Is your feature request related to a problem? Please describe.**
I wonder for a long time now why file explorer is not able to pin files to the sidebar.
Sometimes this could be a valuable feature having one or a few files just very good available in the left navigation bar.

**Describe the solution you'd like**
Maybe you could add the option to pin also files to the sidebar and not just folders? I think this is really handy in some situations.

**Describe alternatives you've considered**
When clicking on the files in the sidebar they should of course get opened. 

**Additional context**
Currently in Windows 10 you also cannot pin files to the taskbar, and also not to the startmenu, you are just able to send a link to the deskop)

**Comment by yaichenbaum** [comment]
How would we differentiate between files and folders? Users expect the sidebar to be a spot to navigate to directories. This will obviously only happen if the users actually pins the file but I am not sure if the option to do that should even be there.
I would like some input on this feature request from the community and how they feel about this. I am pinning this issue to increase discoverability.

**Comment by yaichenbaum** [comment]
One possibility would be to have a section labeled **Files** that would be where pinned files would go but it would need to remove the label that says "Files" when there is nothing pinned.

**Comment by szaimen** [comment]
> One possibility would be to have a section labeled Files that would be where pinned files would go but it would need to remove the label that says "Files" when there is nothing pinned.

That sounds like a good idea and compromise for me and additionally would remain the current UX-concept (of only accessing folders in the navigation bar).

**Comment by duke7553** [comment]
I thought about this proposal, and pinning individual files to the sidebar isn't useful to enough users. Regardless, the sidebar is intended to get users to their destination, rather than be the destination. This is why that idea conflicts with the design metaphor. However, we're investigating ways to better enhance discoverability of relevant items using the home page.

**Comment by yaichenbaum** [comment]
I personally have some files I frequently open, for example the sln for Files UWP, having these pinned to a quick access section at the top of the sidebar would be helpful. I don't necessarily want to navigate to the directory and find the correct file there in order to open it.
I can see that some users won't want this but making it optional can solve that concern.

**Comment by szaimen** [comment]
So reopen?

**Comment by duke7553** [comment]
I'll re-open this, but we should still consider changes to the new tab page to improve discoverability.

**Comment by yaichenbaum** [comment]
After discussing this issue we have come to the conclusion that the sidebar should be limited to bringing users a location, and that opening files shouldn't be included. The replacement for this would be including a widget on the home page where users can pin files for ease of access,. Merging with #366.
