### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by SebastianZHD** [files-community/files-uwp#756]
1) Include a "This PC" button on the left that shows the traditional "This PC" screen with logical drives listed

2) Enable "tree view" with the tabs on the left

3) Allow a large and small size for the tabs on the left. Having them big is great for touchscreens, but it's frustrating on the desktop

4) Allow resizing the file/folder listings in the main view with further granularity beyond "List view" and "Grid view", adding UI toggles for this or just holding "CTRL and +/-" or "CTRL + and scrolling" is good for this

**Comment by xPoppyx** [comment]
>     4. Allow resizing the file/folder listings in the main view with further granularity beyond "List view" and "Grid view", adding UI toggles for this or just holding "CTRL and +/-" or "CTRL + and scrolling" is good for this


this feature has been added, take a look at the latest version of the app

**Comment by duke7553** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
